version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd bmoodify
      - npm install

  build:
    commands:
      - cp -r * ../

artifacts:
  base-directory: bmoodify
  files:
    - '**/*'
